services:
  sql-injection-login:
    build:
      context: ./labs/sql-injection-login
    container_name: vulnmentor-sqli-lab
    ports:
      - "4010:4010"
    restart: unless-stopped

  api-broken-auth:
    build:
      context: ./labs/api-broken-auth
    container_name: vulnmentor-api-bola-lab
    ports:
      - "4020:4020"
    restart: unless-stopped

  api-jwt-tampering:
    build:
      context: ./labs/api-jwt-tampering
    container_name: vulnmentor-api-jwt-lab
    ports:
      - "4030:4030"
    restart: unless-stopped

  api-rate-limit-bypass:
    build:
      context: ./labs/api-rate-limit-bypass
    container_name: vulnmentor-api-rate-limit-lab
    ports:
      - "4040:4040"
    restart: unless-stopped
